apiVersion: v1
kind: Service
metadata:
  name: caprover-service
spec:
  type: LoadBalancer
  selector:
    app: caprover-sandbox
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: app
    protocol: TCP
    port: 3000
    targetPort: 3000
